export const MOGADISHU_DISTRICTS = [
  'Abdiaziz',
  'Bondhere',
  'Daynile',
  'Dharkenley',
  'Hamar Jajab',
  'Hamar Weyne',
  'Hodan',
  'Howlwadaag',
  'Kahda',
  'Karaan',
  'Shangani',
  'Shibis',
  'Waberi',
  'Wadajir',
  'Warta Nabada',
  'Yaqshid',
  'Garasbaaley',
  'Daarusalaam',
  'Gubadley',
  'Huriwaa',
];
